apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyzdo-persist-worker
  namespace: pyzdo-dev
  labels:
    app: pyzdo-persist-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyzdo-persist-worker
  template:
    metadata:
      labels:
        app: pyzdo-persist-worker
    spec:
      containers:
        - name: pyzdo-persist-worker
          image: pyzdo-persist-worker:latest
          imagePullPolicy: Never
          env:
            - name: GROUP_ID
              value: "persist_worker_001"
            - name: BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: WORKER_TOPIC
              value: "topic_projectm_cmd_persist"
            - name: PERSIST_URL
              value: "http://pyzdo-cb-api:8003/cb/cmd"
            - name: BULK_PERSIST_URL
              value: "http://pyzdo-cb-api:8003/cb/cmds"
            - name: STORE_QUERY_URL
              value: "http://pyzdo-cb-api:8003/cb/qry"
