from enum import Enum


class CmdTypes(Enum):
    GATHER_PROJECT_UNITS_OF_WORK = "GATHER_PROJECT_UNITS_OF_WORK"
    BUILD_WORK_ITEM_TREE = "BUILD_WORK_ITEM_TREE"
    BUILD_WEIGHTED_WORK_ITEM_TREE = "BUILD_WEIGHTED_WORK_ITEM_TREE"
