FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine as restore-build-publish

WORKDIR /src

COPY ./src/Azdo.Proxy.Api/. .

RUN dotnet restore .

RUN dotnet publish . --no-restore --configuration Release --output /publish

from mcr.microsoft.com/dotnet/aspnet:7.0 as final
# from mcr.microsoft.com/dotnet/sdk:7.0 as final

# COPY ./aspnetcore-localhost-77A1A17FA279DF628F700A5AFF3442DB63D011AA.pfx /usr/local/share/ca-certificates/
COPY ./nscacert.pem /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN mkdir /app

WORKDIR /app

COPY --from=restore-build-publish /publish /app


ENTRYPOINT ["dotnet", "Azdo.Proxy.Api.dll"]


# dotnet user-secrets -p /app/azdo.proxy.api.csproj set "Kestrel:Certificates:Development:Password" crypticpassword
