# mandy-cb-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandy-cb-api
  namespace: project-m-dev
  labels:
    app: mandy-cb-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mandy-cb-api
  template:
    metadata:
      labels:
        app: mandy-cb-api
    spec:
      containers:
        - name: mandy-cb-api
          image: project-m-mandy-cb-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: COUCHBASE_HOST
              value: "mandy-db"
            - name: COUCHBASE_USERNAME
              value: "root"
            - name: COUCHBASE_PASSWORD
              value: "R007__.."
---
apiVersion: v1
kind: Service
metadata:
  name: mandy-cb-api
  namespace: project-m-dev
spec:
  selector:
    app: mandy-cb-api
  type: ClusterIP
  ports:
    - name: port-8003
      protocol: TCP
      port: 8003
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ext-mandy-cb-api
  namespace: project-m-dev
spec:
  selector:
    app: mandy-cb-api
  type: LoadBalancer
  ports:
    - name: port-8005
      protocol: TCP
      port: 8005
      targetPort: 8001
---
