apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandy-ui
  namespace: project-m-dev
  labels:
    app: mandy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mandy-ui
  template:
    metadata:
      labels:
        app: mandy-ui
    spec:
      containers:
        - name: mandy-ui
          image: project-m-mandy-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: VUE_APP_AZDO_API_KEY
              value: "xyz"
            - name: VUE_APP_DEFAULT_QUERY_FOLDER
              value: "Shared Queries/Customers and Emerging Markets/Rapid Response/N2 Chapmans Peak Project Team/Reboot"
            - name: VUE_APP_UI_API_BASE_URL
              value: "http://localhost:3004/ui-api"
---
apiVersion: v1
kind: Service
metadata:
  name: ext-mandy-ui
  namespace: project-m-dev
spec:
  selector:
    app: mandy-ui
  type: LoadBalancer
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 80
---
