apiVersion: batch/v1
kind: Job
metadata:
  name: init
  namespace: project-m-dev
spec:
  template:
    spec:
      containers:
        - name: init
          image: confluentinc/cp-kafka:7.4.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              kafka-topics --bootstrap-server kafka-service:9092 --list

              echo -e 'Creating kafka topics'

              kafka-topics --bootstrap-server kafka-service:9092 --create --if-not-exists --topic topic_projectm_cmd_persist --replication-factor 1 --partitions 1
              kafka-topics --bootstrap-server kafka-service:9092 --create --if-not-exists --topic topic_projectm_cmd_insights_gather --replication-factor 1 --partitions 1
              kafka-topics --bootstrap-server kafka-service:9092 --create --if-not-exists --topic topic_projectm_cmd_insights_structure --replication-factor 1 --partitions 1
              kafka-topics --bootstrap-server kafka-service:9092 --create --if-not-exists --topic topic_projectm_cmd_azdo_proxy --replication-factor 1 --partitions 1

              echo -e 'Successfully created the following topics:'
              kafka-topics --bootstrap-server kafka-service:9092 --list
      restartPolicy: OnFailure
  backoffLimit: 4
