apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: project-m-dev
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: debezium/kafka
          ports:
            - containerPort: 9092
              name: kafka
          env:
            - name: BROKER_ID
              value: "0"
            - name: ZOOKEEPER_CONNECT
              value: "host.docker.internal:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
